core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('login',views.loginPage, name='login'),   
    path('register/', views.registerPage, name="register"),   
    path('loans/', views.loans, name='loans'),
    path('logout/', views.logoutUser, name='logout'),
    path('clients_list/', views.clients_list_view, name='viewclient'),
    path('loan/account/', views.create_loanaccount, name='createloan'),
    path('loan/account/<str:pk>/', views.show_allloandets, name='loandetails'),
    path('loan/update/<str:pk>/', views.update_loan_view, name='updateloandetails'),
    path('loan/delete/<str:pk>/', views.delete_loanaccount, name='deleteloan'),
    path('viewperm/', views.view_permissions, name='permit'),
    path('search/', views.SearchClientsView.as_view(), name='SearchClients'),
    path('search_user/', views.SearchUserView.as_view(), name='SearchUsers'),
    path('client/create/', views.create_client_view, name='createclient'),
    path('client/edit/<str:pk>/', views.update_client_view, name='editclient'),
    path('client/delete/<str:pk>/', views.client_inactive_view, name='deleteclient'),
    path('client/profile/<str:pk>/', views.client_profile_view, name='clientprofile'),
    path('client/profile/update/<str:pk>/', views.updateclientprofileview, name='updateclientprofile'),
    path('users/list/', views.users_list_view, name='userslist'),
    path('user/create/', views.create_user_view, name='createuser'),
    path('user/edit/<str:pk>/', views.update_user_view, name='edituser'),
    path('user/profile/<str:pk>/', views.user_profile_view, name='userprofile'),
    path('user/delete/<str:pk>/', views.user_inactive_view, name='deleteuser'),
    path('payments/payloan/', views.loan_payment, name='payloan'),
]

microfinance/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
]

core/models.py
from multiprocessing.sharedctypes import Value
from django.db import models
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin,User,Permission


GENDER_TYPES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

USER_ROLES = (
    ('OfficeAdmin', 'OfficeAdmin'),
    ('Supervisor', 'Supervisor'),
    ('LoanOfficer', 'LoanOfficer'),
    ('Cashier', 'Cashier')
)

ACCOUNT_STATUS = (
    ('Applied', 'Applied'),
    ('Withdrawn', 'Withdrawn'),
    ('Approved', 'Approved'),
    ('Rejected', 'Rejected'),
    ('Closed', 'Closed'),
)


INTEREST_TYPES = (
    ('Flat', 'Flat'),
    ('Declining', 'Declining'),
)

RECEIPT_TYPES = (
    ('EntranceFee', 'EntranceFee'),
    ('MembershipFee', 'MembershipFee'),
    ('BookFee', 'BookFee'),
    ('LoanProcessingFee', 'LoanProcessingFee'),
    ('AdditionalSavings', 'AdditionalSavings'),
    ('LoanDeposit', 'LoanDeposit'),
)

FD_RD_STATUS = (
    ('Opened', 'Opened'),
    ('Paid', 'Paid'),
    ('Closed', 'Closed'),
)

PAYMENT_TYPES = (
    ('Loans', 'Loans'),
    ('LoanProcessingFee', 'LoanProcessingFee'),
    ('Penalty', 'Penalty'),
)
PAYMENT_METHODS = (
    ('Paypal','Paypal'),
    ('Stripe','Stripe'),
    ('Payoneer','Payoneer')
)



class UserManager(BaseUserManager):
    def create_superuser(self, username, first_name, email, password, **other_fields):
        other_fields.setdefault('is_admin', True)
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        if other_fields.get('is_staff') is not True:
            raise ValueError('SuperUser must be assigned to is_staff=True')
        if other_fields.get('is_admin') is not True:
            raise ValueError('SuperUser must be assigned to is_admin=True')
        return self.create_user(username, first_name, email, password, **other_fields)

    def create_user(self, username,first_name, email, password,**other_fields):
        if not username:
            raise ValueError('Users must have an username')

        # Save the user
        email = self.normalize_email(email)
        user = self.model(username=username,email=email,first_name=first_name,**other_fields)
        user.set_password(password)
        user.is_staff = True
        user.save()
        return user

    


class User(AbstractBaseUser,PermissionsMixin):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, null=True)
    user_roles = models.CharField(choices=USER_ROLES, max_length=20)
    date_of_birth = models.DateField(default='2000-01-01', null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    county = models.CharField(max_length=50, null=True)
    subcounty = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    area = models.CharField(max_length=150, null=True)
    mobile = models.CharField(max_length=10, default='0', null=True)
    pincode = models.CharField(default='', max_length=10, null=True)
    user_permissions = models.ManyToManyField(
        Permission, related_name='user_permissions', blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS=['email','first_name']

    def __unicode__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        if self.is_active and self.is_admin:
            return True
        # return _user_has_perm(self, perm, obj)
        else:
            try:
                user_perm = self.user_permissions.get(codename=perm)
            except ObjectDoesNotExist:
                user_perm = False

            return bool(user_perm)

    class Meta:
        permissions = (
            ("OfficeAdmin",
             "Can manage all users accounts."),
            ("Add_user","Can add user accounts."),
            ("edit_clients","Can edit client accounts."),
            ("view_clients","Can view client accounts."),
            ("manage_clients","Can manage client accounts."),
        )


class Client(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    national_id= models.PositiveIntegerField(default=0)
    email = models.EmailField(max_length=255, null=True)
    created_by = models.ForeignKey(User,on_delete=models.PROTECT)
    account_number = models.CharField(max_length=50, unique=True)
    date_of_birth = models.DateField()
    gender = models.CharField(choices=GENDER_TYPES, max_length=10)
    occupation = models.CharField(max_length=200)
    annual_income = models.BigIntegerField()
    country = models.CharField(max_length=50)
    county = models.CharField(max_length=50)
    subcounty = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    area = models.CharField(max_length=150)
    mobile = models.CharField(max_length=20, default=True, null=True)
    pincode = models.CharField(max_length=20, default=True, null=True)
    photo = models.ImageField(upload_to=settings.PHOTO_PATH, null=True)
    signature = models.ImageField(upload_to=settings.SIGNATURE_PATH, null=True)
    is_active = models.BooleanField(default=True)
    is_client = models.BooleanField(default=True)
    status = models.CharField(max_length=50, default="UnAssigned", null=True)
    bookfee_amount = models.DecimalField(max_digits=19, decimal_places=6, default=0)

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()
    def __str__(self):
        return f"{self.first_name},{self.last_name}"
    
    @property
    def get_loan(self):
        self.loan=LoanAccount()
        if self.loan.client == self:
            return self.loan
    


class LoanRepaymentEvery(models.Model):
    value = models.IntegerField()


class LoanAccount(models.Model):
    account_no = models.CharField(max_length=50, unique=True)
    interest_type = models.CharField(choices=INTEREST_TYPES, max_length=20)
    client = models.ForeignKey(Client, null=True, blank=True,on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.PROTECT)
    status = models.CharField(choices=ACCOUNT_STATUS, max_length=20)
    opening_date = models.DateField(auto_now_add=True, blank=True)
    approved_date = models.DateField(null=True, blank=True)
    loan_issued_date = models.DateField(null=True, blank=True)
    loan_issued_by = models.ForeignKey(User, null=True, blank=True, related_name="loan_issued_by",on_delete=models.PROTECT)
    closed_date = models.DateField(null=True, blank=True)
    loan_amount = models.DecimalField(max_digits=19, decimal_places=6)
    loan_repayment_period = models.IntegerField()
    loan_repayment_every = models.IntegerField()
    loan_repayment_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True)
    total_loan_amount_repaid = models.DecimalField(max_digits=19, decimal_places=6, default=0)
    loanpurpose_description = models.TextField()
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    interest_charged = models.DecimalField(max_digits=19, decimal_places=6, default=0)
    total_interest_repaid = models.DecimalField(max_digits=19, decimal_places=6, default=0)
    total_loan_paid = models.DecimalField(max_digits=19, decimal_places=6, default=0)
    total_loan_balance = models.DecimalField(max_digits=19, decimal_places=6, default=0)
    loanprocessingfee_amount = models.DecimalField(max_digits=19, decimal_places=6, default=0)
    no_of_repayments_completed = models.IntegerField(default=0)

    def __unicode__(self):
        return self.account_no
    
    def __str__(self):
        return self.account_no
    


class Receipts(models.Model):
    date = models.DateField()
    receipt_number = models.CharField(max_length=50, unique=True)
    client = models.ForeignKey(Client, null=True, blank=True,on_delete=models.PROTECT)
    entrancefee_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    membershipfee_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    bookfee_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    loanprocessingfee_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    recurringdeposit_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    loanprinciple_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    loaninterest_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    insurance_amount = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    staff = models.ForeignKey(User,on_delete=models.PROTECT)
    savings_balance_atinstant = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True)
    demand_loanprinciple_amount_atinstant = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    demand_loaninterest_amount_atinstant = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)
    principle_loan_balance_atinstant = models.DecimalField(max_digits=19, decimal_places=6, null=True, blank=True, default=0)

    def __unicode__(self):
        return self.receipt_number

    def __str__(self):
        return self.receipt_number


class Payments(models.Model):
    date = models.DateField()

templates/loan/account.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li><a href="{% url 'micro_admin:branchprofile' loanaccount.client.branch.id %}">{{ loanaccount.client.branch.name|capfirst }} Branch</a></li>
<li><a href="{% url 'micro_admin:clientprofile' loanaccount.client.id %}">{{ loanaccount.client.first_name|capfirst }} Member</a></li>
<li><a href="{% url 'loans:clientloanaccountslist' loanaccount.client.id %}">Loans</a></li>
<li>Loan Account - {{ loanaccount.account_no }}</li>
{% endblock %}
{% block content %}
<!--content goes below-->
<div class="container">
  <div class="wrap-cp-div margin-top-set">
    <div class="btn-row" >
      {% if user.is_admin or user.user_roles == "BranchManager" %}
      {% if loanaccount.status == "Approved" %}
      <button title="Already Approved"><i class="fa fa-check-circle-o padd"></i>Approved</button>
      {% else %}
      <a class='change-loan-account-status' data-href="{% url 'loans:change_loan_account_status' loanaccount.id %}?status=Approved"><button id="approve-button"><i class="fa fa-check-circle-o padd"></i>Approve</button></a>
      {% endif %}
      {% if loanaccount.status == "Withdrawn" %}
      <button title="Already Withrawn"><i class="fa fa-arrow-circle-o-down padd"></i>Withdrawn</button>
      {% else %}
      <a class='change-loan-account-status' data-href="{% url 'loans:change_loan_account_status' loanaccount.id %}?status=Withdrawn"><button id="withdraw-button"><i class="fa fa-arrow-circle-o-down padd"></i>Withdraw</button></a>
      {% endif %}
      {% if loanaccount.status == "Rejected" %}
      <button title="Already Rejected"><i class="fa fa-times-circle-o padd"></i>Rejected</button>
      {% else %}
      <a class='change-loan-account-status' data-href="{% url 'loans:change_loan_account_status' loanaccount.id %}?status=Rejected"><button id="reject-button"><i class="fa fa-times-circle-o padd"></i>Reject</button></a>
      {% endif %}
      {% if loanaccount.status == "Closed" %}
      <button title = "Already Closed"><i class="fa fa-trash-o padd"></i>Closed</button>
      {% else %}
      <a class='change-loan-account-status' data-href="{% url 'loans:change_loan_account_status' loanaccount.id %}?status=Closed"><button id="close-button"><i class="fa fa-trash-o padd"></i>Close</button></a>
      {% endif %}
      <br clear="all" />
      {% endif %}
    </div>
  </div>
</div>
<!--form div starts below-->
<div class="panel panel-default wrap-cp-div">
  <div class="panel-heading min-ht-res-60">
    <h3 class="panel-title">
      {% if loanaccount.client.is_active %}
      <i class="fa fa-square green padd"></i>
      {% else %}
      <i class="fa fa-square red padd"></i>{% endif %}
      {{ loanaccount.client.first_name|capfirst }} Loan Account
    </h3>
    <span class="mar-tp-m mar-top-m24">
    <a href="{% url 'loans:listofclientloandeposits' loanaccount.client.id loanaccount.id %}" class="view-tab-btn"><i class="fa fa-eye padd"></i>View Loan Deposits</a>
    <a href="{% url 'loans:clientloanledgeraccount' loanaccount.client.id loanaccount.id %}" class="view-tab-btn">Ledger</a>
    {% if user.is_admin == 0 and user.user_roles != "BranchManager" %}
    {% if loanaccount.status == "Withdrawn" %}
    <a  title="Already Withrawn" class="view-tab-btn"><i class="fa fa-arrow-circle-o-down padd"></i>Withdrawn</a>
    {% else %}
    <a data-href="{% url 'loans:change_loan_account_status' loanaccount.id %}?status=Withdrawn" id="withdraw-button" class="view-tab-btn change-loan-account-status"><i class="fa fa-arrow-circle-o-down padd"></i>Withdraw</a>
    {% endif %}
    {% endif %}
    </span>
  </div>
  <div class="panel-body">
    <!--panel body starts above-->
    <form id="loanaccountform" class="form-horizontal" role="form">
      {% csrf_token %}
      <!--div 1 0f form-->
      <div class="box-form">
        <div class="form-group grp-view">
          <input type="hidden"  id="loanaccount_id" value="{{ loanaccount.id }}" style="dispaly:none;">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Loan A/C Number :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.account_no }}</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Applied By Staff :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.created_by|capfirst }}</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Loan Issued By :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.loan_issued_by|capfirst }}</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Loan Amount :</label><span class="col-lg-6 mar-top" style="color:#FF00CC;">{{ loanaccount.loan_amount }}/-</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Loan Repayment Period :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.loan_repayment_period }} Months</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Principle Repayment Amount :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top" style="color:#337ab7;">{{ loanaccount.principle_repayment }}/-</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Total Loan Repayment Amount :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.loan_repayment_amount }}/-</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label"> Total Principle Repaid Amount  :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.total_loan_amount_repaid }}/-</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label"> Total Loan Amount Paid :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.total_loan_paid }}/-</span>
        </div>
      </div>
      <!--div 1 of fomr ends above-->
      <!--div 2 of form starts below-->
      <div class="box-form">
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Opened On :</label><span class="col-lg-6 col-sm-6 col-xs-6mar-top">{{ loanaccount.opening_date }}</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Status :</label>
          {% if loanaccount.status == "Applied" %}
          <span class="col-lg-6 col-sm-6 col-xs-6 mar-top" style="color:#337ab7;">
          {% elif loanaccount.status == "Withdrawn" %}
          <span class="col-lg-6 col-sm-6 col-xs-6 mar-top" style="color:#FF6600;">
          {% elif loanaccount.status == "Approved" %}
          <span class="col-lg-6 col-sm-6 col-xs-6 mar-top" style="color:#008000;">
          {% elif loanaccount.status == "Rejected" %}
          <span class="col-lg-6 col-sm-6 col-xs-6 mar-top red">
          {% elif loanaccount.status == "Closed" %}
          <span class="col-lg-6 col-sm-6 col-xs-6 mar-top" style="color:#660099;">
          {% endif %}
          {{ loanaccount.status }}
          {% if loanaccount.status == "Approved" %}&nbsp; on&nbsp; {{ loanaccount.approved_date }}{% endif %}</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Loan Issued On :</label>
            <span class="col-lg-6 col-sm-6 col-xs-6 mar-top">
              {% if loanaccount.loan_issued_date %}
                {{ loanaccount.loan_issued_date }}
              {% else %}
                -
              {% endif %}
              <!-- {% if user.is_admin and not loanaccount.loan_issued_date %}
              <a href="{% url 'loans:issueloan' loanaccount.id %}" style="text-decoration:none; color:#fff; margin-left:3px;" title="Issue Loan"><i class="fa fa-pencil-square-o trash-icon"></i></a>
              {% endif %} -->
          </span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Annual Interest Rate:</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.annual_interest_rate }} % {{loanaccount.interest_type}} Interest</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Loan Repayment for Every :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.loan_repayment_every }} Month{{ loanaccount.loan_repayment_every|pluralize }}</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Interest Charged :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top" style="color:#337ab7;">{{ loanaccount.interest_charged }}/-</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">No. of Repayments Completed :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ no_of_repayments_completed }}</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label"> Total Interest Repaid :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.total_interest_repaid }}/-</span>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Total Principle Balance :</label><span class="col-lg-6 col-sm-6 col-xs-6 mar-top">{{ loanaccount.total_loan_balance }}/-</span>
        </div>
      </div>
      <br clear="all" />
    </form>
  </div>
  <!--panel body ends below crct-->
</div>
{% if loan_disbursements %}
<!-- Loan Disbursements-->
<div class="panel panel-default wrap-cp-div">
  <div class="panel-heading min-ht-res-60" style="background: #03A9F4;">
    <h3 class="panel-title">Loan Disbursements</h3>
  </div>
  <div class="panel-body pb-table">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr class="head-row-tb">
            <th>S.No</th>
            <th>Date</th>
            <th>Vocher Number</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody class="body-row-tb">
          {% for each in loan_disbursements %}
            <tr>
              <td><b>{{ forloop.counter }}</b></td>
              <td>{{ each.date }}</td>
              <td>{{ each.voucher_number}}</td>
              <td>{{ each.total_amount|floatformat:2 }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- /Loan Disbursements-->
{% endif %}
<script type="text/javascript">
  $(document).ready(function() {
    $('.change-loan-account-status').click(function(e) {
      e.preventDefault();
      submit_url = $(this).attr("data-href")
      $.post(submit_url, $('#loanaccountform').serialize(), function(data) {
        if (data.error) {
          alert(data.error_message);
        }
        else {
          alert("Member Loan status changed successfully.")
          window.location = '.';
        }
      }, "json");
    });
  });
</script>
{% endblock content%}

templates/loan/edit.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<!--content goes below-->
<main style="margin-top: 58px">
  <div class="container pt-4">
    <form method="POST" action="">
    {% csrf_token %}
    <div id="div_id_account_no" class="form-group" hidden>
        <label for="id_account_no" class="requiredField">Account no<span class="asteriskField">*</span></label>
        <div>
        <input type="text" name="account_no" value="{{loan.account_no}}" maxlength="50" 
        class="textinput textInput form-control" required="" id="id_account_no"/>
        </div>
    </div>
    <div id="div_id_client" class="form-group" hidden>       
        <div class="div_id_client" hidden>          
            <select class="md-form mdb-select" name="client" id="client">                
                <option value="{{loan.client.id}}">{{loan.client}}</option>  
            </select>
        </div>
    </div>
    </div>
    <div id="div_id_interest_type" class="form-group">
        <label for="id_interest_type" class="requiredField">
        Interest type<span class="asteriskField">*</span>
        </label>
        <div>
        <select name="interest_type" class="select form-control" required=""id="id_interest_type">
            <option value="">---------</option>
            <option value="Flat">Flat</option>
            <option value="Declining" selected="">Declining</option>
        </select>
        </div>
    </div>
    <div id="div_id_interest_rate" class="form-group">
        <label for="id_interest_rate" class="requiredField">Interest rate<span class="asteriskField">*</span></label>
        <div>
        <input type="number" name="interest_rate" value="{{loan.interest_rate}}" step="0.01" class="numberinput form-control" required="" id="id_interest_rate"/>
        </div>
    </div>
    <div id="div_id_loan_amount" class="form-group">
        <label for="id_loan_amount" class="requiredField">
        Loan amount<span class="asteriskField">*</span>
        </label>
        <div>
        <input type="number" name="loan_amount" value="{{loan.loan_amount}}" step="0.000001" class="numberinput form-control" required="" id="id_loan_amount"/>
        </div>
    </div>
    <div id="div_id_loan_repayment_period" class="form-group">
        <label for="id_loan_repayment_period" class="requiredField">Loan repayment period<span class="asteriskField">*</span></label>
        <div>
        <input type="number" name="loan_repayment_period" value="{{loan.loan_repayment_period}}" class="numberinput form-control" required="" id="id_loan_repayment_period"/>
        </div>
    </div>
    <div id="div_id_loan_repayment_every" class="form-group">
        <label for="id_loan_repayment_every" class="requiredField"> Loan repayment every<span class="asteriskField">*</span></label>
        <div> <input type="number" name="loan_repayment_every" value="{{loan.loan_repayment_every}}" class="numberinput form-control" 
            required="" id="id_loan_repayment_every"/>
        </div>
    </div>
    <div id="div_id_loanpurpose_description" class="form-group">
        <label for="id_loanpurpose_description" class="requiredField"> Loanpurpose description<span class="asteriskField">*</span> </label>
        <div> <textarea name="loanpurpose_description" cols="40" rows="10" class="textarea form-control" required="" 
            id="id_loanpurpose_description" spellcheck="false">{{loan.loanpurpose_description}}</textarea>
        </div>
    </div>

    <div class="btns-row">
        <div class="form-group btns align-btns">
        <button class="btn btn-success"> <i class="fa fa-check padd"></i> Submit </button>
        <button class="btn btn-dark" type="reset"><i class="fa fa-times padd"></i> Cancel </button>
        </div>
    </div>
    </form>
 </div>
</main>
{% endblock content %}

templates/loan/editloan.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<!--content goes below-->
<main style="margin-top: 58px">
  <div class="container pt-4">
    <form method="POST" action="">
     {% csrf_token %}
      {{form | crispy}}
      <div class="btns-row">
        <div class="form-group btns align-btns">
         <button class="btn btn-success"><i class="fa fa-check padd"></i> Submit</button>
         <button class="btn btn-dark " type="reset"><i class="fa fa-times padd"></i> Cancel</button>
        </div>
      </div>
    </form>
    
  </div>
</main>
{% endblock content %}